name: Lint and Static Analysis

# Trigger on pushes or pull requests to branches matching 'alexandre_assignment2'
on:
  push:
    branches: ['alexandre_assignment2']
  pull_request:
    branches: ['alexandre_assignment2']

jobs:
  clang-tools:
    name: Run clang-tidy and clang-format
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (This copies the repo into the virtual machine)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install necessary tools (here we have to use the package manager of ubuntu not Arch!)
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang-tidy clang-format cmake build-essential libvtk9-dev

      # Step 3: Cache CMake configuration to speed up future runs. This uses the same cache key as the build and test workflow i.e. this cache is shared across workflows.
      - name: Cache CMake configuration
        uses: actions/cache@v4
        with:
          path: |
            build/CMakeCache.txt
            build/CMakeFiles
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      # Step 4: Configure CMake (needed to generate build system)
      - name: Configure project
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON # the extra flag is needed here so that clang tidy can find include paths and compiler flags

      # Step 5: Run clang-tidy using your custom target
      - name: Run clang-tidy
        run: cmake --build build --target run_clang_tidy

      # Step 6: Check code formatting using your custom target
      - name: Run clang-format check
        run: cmake --build build --target clang_format_check

