name: Lint and Static Analysis

# Trigger on pushes or pull requests to branches matching 'alexandre_assignment2'
on:
  push:
    branches: ['alexandre_assignment2']
  pull_request:
    branches: ['alexandre_assignment2']

jobs:
  clang-tools:
    name: Run clang-tidy and clang-format
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (This copies the repo into the virtual machine)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache APT packages to speed up installs. This Caches the downloaded packages on a GitHub cache.
      # This cache can be accessed acoss branches
      # This avoids the long downloads from mirrors every time the workflows run.
      # The "|" isn't an OS pipe but indicates a multiline string literal
      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      # Step 3: Install necessary tools (here we have to use the package manager of ubuntu not Arch!)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy clang-format cmake build-essential libvtk9-dev

      # Step 4: Cache CMake configuration to speed up future runs. This uses the same cache key as the build and test workflow i.e. this cache is shared across workflows.
      # Because the cache key is determined by "${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}" changes to the source files do not invalidate the cache.
      # Only changing any of the CMakeLists.txt or *.cmake files invalidate the cache.
      - name: Cache CMake configuration
        uses: actions/cache@v4
        with:
          path: |
            build/CMakeCache.txt
            build/CMakeFiles
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cmake-
      # the last line makes the runner use an older cache if there isn't an exact match. This avoids full cache misses.

      # Step 5: Configure CMake (needed to generate build system)
      - name: Configure project
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON # the extra flag is needed here so that clang tidy can find include paths and compiler flags

      # Step 6: Run clang-tidy using your custom target
      - name: Run clang-tidy
        run: cmake --build build --target run_clang_tidy

      # Step 7: Check code formatting using your custom target
      - name: Run clang-format check
        run: cmake --build build --target clang_format_check

